### ISSUE TITLE
Diagonal tracks

### ISSUE THREAD

**Issue by chennon-aeolus** [linjonathan/tropical_cyclone_risk#10]
Any insight as to why one might get some tracks that look realistic and some that are linear? This example is a n=20 tracks from 2023. There are about 5 out of 20 that look realistic and 15 straight lines. Thanks.
![2023_full_tracks_sel_seeding](https://github.com/user-attachments/assets/01546a0d-d1f5-4587-bf19-97dfdb808475)

**Comment by linjonathan** [comment]
Could you take a look at this issue:

https://github.com/linjonathan/tropical_cyclone_risk/issues/4
