### ISSUE TITLE
ERA-5 input data

### ISSUE THREAD

**Issue by alexandrefierro** [linjonathan/tropical_cyclone_risk#2]
Greetings Jonathan:

Does your repo contain all the necessary input ERA-5 data for the last ~5-10 years for users to be able to run a quick test? Rationale for asking is that requesting these files via the standard c = cdsapi.Client() is extremely slow and often fails with connection errors (likely because the data reside on tape systems). The ECMWF MARS server is no better. The ERA-5 files used are generally quite small so adding them as a standalone tar ball in this repo or on a separate SFTP server would be very useful.

Cheers and thanks,

**Comment by linjonathan** [comment]
Unfortunately, providing the dataset would be too large for a repo, since we need daily zonal and meridional wind fields at both 250- and 850-hPa (it's possible though, but would be on the order of a few GB for 5 years). Did you try the provided script to download the ERA5 data? You can restrict it to 5 years in the namelist.

**Comment by alexandrefierro** [comment]
Good afternoon Jonathan:

Yes; I am familiar with this (modified) ERA5 download script & restricted the retrieval to the last 5-6 years but the data transfer still takes quite a bit of time to reach completion on our Linux cluster (despite the very useful pooling tool you use). Many of the individual transfers are interrupted with:
WARNING HTTP error: [500 Internal Server Error]. Attempt 1 of 500.
before resuming; hence my query.

Thank you.

**Comment by linjonathan** [comment]
Perhaps the ERA5 server was inundated at the time of your request -- in my experience, running the download script has been very quick. I could look into providing a low-resolution version of the datasets, but I'm sorry I don't have a better answer right now!

**Comment by wcarthur** [comment]
The CDS is being upgraded, and they note that some disruptions are possible. I've found that some periods are very slow.

**Comment by krober10nd** [comment]
I've recently experienced the same issue as of today (Oct. 4, 2024). Some files do not successfully download then when you go to run, dask throws a segmentation fault as the files can't be found.

**Comment by linjonathan** [comment]
I'll consider adding some test fields in a Zenodo repository in the future!

**Comment by krober10nd** [comment]
FYI Copernicus has decided to now call "time" "valid_time" which breaks all the scripts.

**Comment by krober10nd** [comment]
In files with SLP they've now went with "date" for the time variable complicating things further.

**Comment by chennon717** [comment]
> FYI Copernicus has decided to now call "time" "valid_time" which breaks all the scripts.

Yes, the dimension 'time' is hard coded everywhere so scripts fail for u and v ('valid_time') and SLP/SST ('date'). I've been trying workarounds but it is getting out of control.

**Comment by krober10nd** [comment]
I also struggled with this. What I ended up doing is instead of modifying the code, modify the inputs by editing the time variable and make it cf-compliant. It was unprofessional for an organization like Copernicus to modify the naming of variables. I fail to see how changing from time to valid_time or date is helpful. 

I'm testing that now and will post my modification to the download script if it works.

**Comment by chennon-aeolus** [comment]
> I also struggled with this. What I ended up doing is instead of modifying the code, modify the inputs by editing the time variable and make it cf-compliant. It was unprofessional for an organization like Copernicus to modify the naming of variables. I fail to see how changing from time to valid_time or date is helpful.
> 
> I'm testing that now and will post my modification to the download script if it works.

Curious, how did your test go?

**Comment by krober10nd** [comment]
I created a script to modify the downloaded ERA5 inputs. The scripts produce valid environmental winds (they make sense in QGIS) and thermodynamic inputs but when running the downscaling tool, it can't read the time variable in the derived files and it still fails. I'm not sure how to fix the time variable issue still.

```
'''
In late sept 2024, cdsapi started using a new netcdf file format 

'''
import os
from pathlib import Path
import xarray as xr
import pandas as pd

start_year = 1970
#end_year = 2023
end_year = 1970

variables = ['q', 'sp', 'sst', 't', 'u', 'v']

for year in range(start_year, end_year+1):

    for v in variables:

        if v == 'u' or v == 'v':
            time_name = 'valid_time'

            output_file = f'data/era5/{year}/era5_{v}_daily_{year}.nc'

            file_monthly = f'data/era5/{year}/era5_{v}_daily_{year}.nc'
        else:
            time_name = 'date'

            output_file = f'data/era5/{year}/era5_{v}_monthly_{year}.nc'

            file_monthly = f'data/era5/{year}/era5_{v}_monthly_{year}.nc'

        ds_monthly = xr.open_dataset(file_monthly)

        # move the file_monthly to a backup file and up two directories
        # if file doesn't exist in the backup directory, skip
        pth = Path(file_monthly.replace("data/era5", "data/era5_backup"))
        if not pth.exists():
            move_to = f"{file_monthly.replace('data/era5', 'data/era5_backup')}"
            os.system(f'mkdir -p {move_to}')
            cmd = f'cp {file_monthly} {file_monthly.replace("data/era5", "data/era5_backup")}'
            os.system(cmd)
        else: 
            print(f"File already exists in backup directory: {pth}")
            continue
        
        # Convert the integer 'date' to datetime64 format
        if v != 'u' and v != 'v':
            try:    
                date_integers = ds_monthly[time_name].values
                datetime_values= pd.to_datetime(date_integers.astype(str), format='%Y%m%d')
            except:
                continue

        # Create a new 'time' variable to replace the 'date'
        if time_name == 'date':
            ds_monthly = ds_monthly.rename({time_name: 'time'})
            ds_monthly = ds_monthly.assign_coords(time=('date', datetime_values))
            # Drop the old 'date' coordinate
            try:
                ds_monthly = ds_monthly.drop_vars('date')
            except ValueError:
                pass
            # rename the dimension to 'time'
            ds_monthly = ds_monthly.swap_dims({'date': 'time'})
        else:
            ds_monthly = ds_monthly.rename({time_name: 'time'})
            #ds_monthly = ds_monthly.assign_coords(time=('valid_time', datetime_values))
            # Drop the old 'valid_time' coordinate
            try:
                ds_monthly = ds_monthly.drop_vars('valid_time')
            except ValueError:
                pass
            # rename the dimension to 'time'
            try:
                ds_monthly = ds_monthly.swap_dims({'valid_time': 'time'})
            except ValueError:
                pass


        # rename pressure_level to level 
        if 'pressure_level' in ds_monthly:
            ds_monthly = ds_monthly.rename({'pressure_level': 'level'})

        # Save the modified dataset with the new time variable
        ds_monthly.to_netcdf('tmp.nc')

        os.system(f'mv tmp.nc {output_file}')

        print(f"Updated file saved to {output_file}")
```

**Comment by krober10nd** [comment]
This is what the NetCDF looks like however when it's read in using xarray it can't decode the time correctly (however QGIS can). 
<img width="891" alt="Screenshot 2024-10-14 at 4 37 17 PM" src="https://github.com/user-attachments/assets/d60c2621-9c8a-4968-82a0-9cf47e68b822">

**Comment by krober10nd** [comment]
I had to fix the time variable in the inputs after it finished processing and now it's working fine.

```
'''
Fix the thermo and env wind files so xarray can decode the time variable 
'''
import xarray as xr
import pandas as pd

#fn = 'data/era5/env_wnd_era5_197001_202312.nc'
fn = 'data/era5/thermo_era5_197001_202312.nc'
#'thermo_era5_197001_202312.nc'

ds = xr.open_dataset(fn, decode_times=False)

# fix time 
# "[days since 1970-01-01]"
ds['time'] = pd.to_datetime(ds['time'].values, unit='D', origin='1970-01-01')

# change the units of time for all the variables to m/s
for var in ds.data_vars:
    if 'time' in ds[var].coords:
        ds[var].encoding['units'] = 'days since 1970-01-01'
        # get rid of units for time
        ds[var].attrs.pop('units', None)

print(ds)

# save the fixed file
ds.to_netcdf(fn)

```

**Comment by chennon717** [comment]
Thanks for this. Did you get this ValueError when the model tries to load the mslp file to generate the thermo fields (line 20 in util/input.py)?

 ValueError: {'expver', 'number'} is a coordinate in some datasets but not others

Not sure what to make of it.

**Comment by krober10nd** [comment]
I did not experience this error. In what file are your seeing this?

**Comment by chennon717** [comment]
I think there was a conflict with a file from a previous test run. No
longer happening.

**Comment by linjonathan** [comment]
Please see the discussion [here](https://github.com/linjonathan/tropical_cyclone_risk/issues/7#issuecomment-2501749748) on the pull request to fix the netCDF dataset issues (the solution is to just use GRIB).
