### ISSUE TITLE
Definition of drag coefficient

### ISSUE THREAD

**Issue by wcarthur** [linjonathan/tropical_cyclone_risk#6]
Curious to know if the variable `Ck` is actually representing the surface drag coefficient in `Coupled_FAST.py`.  It's labeled as enthalpy when the class is instantiated, but later on this variable is used like it's the drag coefficient (e.g. see line 149). `Cd` is used correctly in calculating CAPE (and hence the potential intensity). 

Labeled as surface enthalpy:
```
class Coupled_FAST(bam_track.BetaAdvectionTrack):
    def __init__(self, fn_wnd_stat, basin, dt_start, dt_s, total_time_s):
        super().__init__(fn_wnd_stat, basin, dt_start, dt_s, total_time_s)

        """ FAST Constants """
        self.Ck = namelist.Ck                       # surface enthalpy coefficient
        self.h_bl = namelist.atm_bl_depth           # boundary layer depth (m)
        self.epsilon = 0.33                         # thermodynamic efficiency
        self.kappa = 0.1                            # dimensionless parameter
        self.beta = 1 - self.epsilon - self.kappa   # dimensionless parameter
```

This is Eq (3) from Emanuel (2017). Here `self.Ck` is used as `Cd`
```
    def _dmdt(self,  clon, clat, v, m, env_wnds, t):
        venti = self._calc_venti(t, clon, clat, env_wnds)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", category=RuntimeWarning)
            dmdt = 0.5 * self.Ck / self.h_bl * ((1 - m) * v - venti * m)
        return(dmdt)
```

I presume if I wanted to modify the surface drag coefficient, then `Ck` is the variable in the code to modify?

**Comment by linjonathan** [comment]
Hi Craig,

Great question!

(In my opinion) The short answer is that this the relative roles of Cd and Ck in the intensification rate equation are still under debate. See [this paper ](https://journals.ametsoc.org/view/journals/atsc/78/12/JAS-D-21-0169.1.xml) for a recent theory on the drag coefficient being important (as opposed to the surface enthalpy coefficient, as in Emanuel and Rotunno (2012)).

For your purposes, Ck and Cd (in those equations) are interchangeable, and I would, as you say, just change "Ck" in those equations to be the surface drag coefficient. This would be valuable if you wanted to, say, increase Cd over land.

Jonathan

**Comment by wcarthur** [comment]
Thanks, just wanted to be clear that I wasn't getting it the wrong way around. I've made a change to the surface drag coefficient  (same as Hamish Ramsay did) to improve the overland decay rates
