### ISSUE TITLE
Maximum sustained wind averaging period 

### ISSUE THREAD

**Issue by krober10nd** [linjonathan/tropical_cyclone_risk#8]
Hi, 

The modeled Maximum Sustained Winds that are modeled by the track generator are representative of what wind averaging period? I would imagine 10-min average. 

You did compare the PDI between measured and modeled datasets so presumably you had to adjust for the differences in averaging periods between agencies/basins?

Thanks,

**Comment by linjonathan** [comment]
No, I did not adjust for differences in averaging periods between basins. As you imply, that is a non-trivial issue in the best-track datasets, and something that is important to do!

The wind output by the model is probably best calibrated to the 1-minute sustained wind.

**Comment by krober10nd** [comment]
Thanks Johnathan. Yes this is a major nuance for application to engineering problems.  I suppose the best source to investigate this is the article on FAST?
